[package]
name = "csp"
version = "0.1.0"
authors = ["Ludo Galabru <ludovic@galabru.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = "0.6.0"
jsonrpc-core = "14.0.5"
serde_json = "1.0.47"
futures = "0.1.28"
tokio-codec = "0.1.1"
tokio-executor = "0.1.9"
tokio-io = "0.1.12"
tokio = "0.1.22"
regex = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.8.1"
