[package]
name = "clarity-lsp"
description = "Language server for Clarity"
version = "0.1.0"
authors = ["Ludo Galabru <ludovic@galabru.com>"]
edition = "2018"
license = "GPL-3.0-only"
keywords = ["blockstack", "blockchain", "clarity", "smart-contract"]
exclude = ["vs-client/**"]
homepage = "https://github.com/lgalabru/clarity-lsp"
repository = "https://github.com/lgalabru/clarity-lsp"
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]

[dependencies]
tower-lsp = "0.6.0"
jsonrpc-core = "14.0.5"
serde_json = "1.0.47"
futures = "0.1.28"
tokio-codec = "0.1.1"
tokio-executor = "0.1.9"
tokio-io = "0.1.12"
tokio = "0.1.22"
regex = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.8.1"
