[package]
name = "clarity-lsp"
description = "Language server for Clarity"
version = "0.1.0"
authors = ["Ludo Galabru <ludovic@galabru.com>"]
edition = "2018"
license = "GPL-3.0-only"
keywords = ["blockstack", "blockchain", "clarity", "smart-contract"]
exclude = ["vs-client/**"]
homepage = "https://github.com/lgalabru/clarity-lsp"
repository = "https://github.com/lgalabru/clarity-lsp"
categories = ["command-line-utilities", "development-tools", "development-tools::build-utils"]

[workspace]
members = [".", "xtask/"]

[dependencies]
async-trait = "0.1"
tower-lsp = "0.10.0"
jsonrpc-core = "14.0.5"
lazy_static = "1.4.0"
serde_json = "1.0.47"
tokio = { version = "0.2", features = ["rt-core"] }
tokio-util = { version = "0.3", features = ["codec"] }
regex = "1.3.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.8.1"
clarity_repl = { package = "clarity-repl", path = "../clarity-repl" }

[dev-dependencies]
tokio = { version = "0.2", features = ["io-std", "macros", "test-util"] }

[profile.dev]
debug = 0

[profile.release]
incremental = true
debug = 0